name: 'Update card in click up'
description: 'With this action after every merge is closed in github you will be able to update your cards in the click up'
author: 'luis12391'
inputs:
  clickup_api_url:
    required: true
  clickup_token:
    required: true
  team_id:
    required: true
  space_name:
    required: true
  new_status:
    required: true
  from_list_name:
    required: true
  to_list_name:
    required: true
  from_list_id:
    required: false
  space_id:
    required: false
  to_list_id:
    required: false
  pr_body:
    required: true
    default: "N/A"
  pr_title:
    required: true
    default: "N/A"
runs:
  using: 'docker'
  image: 'Dockerfile'
