name: 'Update card in click up'
description: 'With this action after every merge is closed in github you will be able to update your cards in the click up'
author: 'luis12391'
inputs:
  action_type:
    required: true
  clickup_api_url:
    required: false
  clickup_token:
    required: false
  team_id:
    required: false
  space_name:
    required: false
  new_status:
    required: false
  from_list_name:
    required: false
  to_list_name:
    required: false
  from_list_id:
    required: false
  space_id:
    required: false
  to_list_id:
    required: false
  pr_body:
    required: false
    default: "N/A"
  pr_title:
    required: false
    default: "N/A"
  short_project_name:
    requiered : false
  branch_name: 
    requiered: false
  project_type:
    requiered: false
outputs:
  card_custom_id:
    description: 'A clickup custom card id'
  version_name:
    description: 'Version of the release'
runs:
  using: 'docker'
  image: 'Dockerfile'
